### ISSUE TITLE
Error on Demo

### ISSUE THREAD

**Issue by redhat12345** [ShuangLI59/person_search#111]
Hi, I am getting the following error. please help me to sort out how to solve this issue. Thanks in advance. 

Traceback (most recent call last):
  File "tools/demo.py", line 114, in <module>
    main(args)
  File "tools/demo.py", line 30, in main
    caffe.mpi_init()
AttributeError: 'module' object has no attribute 'mpi_init'

**Comment by DaisyJiao** [comment]
@redhat12345
Hi, I met the same error with you. Have you solved the problem?

**Comment by sannianyihoushu** [comment]
> Hi, I am getting the following error. please help me to sort out how to solve this issue. Thanks in advance.
> 
> Traceback (most recent call last):
> File "tools/demo.py", line 114, in 
> main(args)
> File "tools/demo.py", line 30, in main
> caffe.mpi_init()
> AttributeError: 'module' object has no attribute 'mpi_init'
Have you solved this problem?thanks
