### ISSUE TITLE
Fail to run prepare_roidb(imdb)

### ISSUE THREAD

**Issue by tankienleong** [ShuangLI59/person_search#43]
Hi, I faced the issue IndexError: list index out of range when I tried to run the training code.
ubuntu@ubuntu-S2600CW:~/Downloads/person_search$ experiments/scripts/train.sh 0 --set EXP_DIR resnet50clear
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ GPU_ID=0
+ NET=resnet50
+ DATASET=psdb
+ array=($@)
+ len=4
+ EXTRA_ARGS='--set EXP_DIR resnet50clear'
+ EXTRA_ARGS_SLUG=--set_EXP_DIR_resnet50clear
+ case $DATASET in
+ TRAIN_IMDB=psdb_train
+ TEST_IMDB=psdb_test
+ PT_DIR=psdb
+ ITERS=50000
++ date +%Y-%m-%d_%H-%M-%S
+ LOG=experiments/logs/psdb_train_resnet50_--set_EXP_DIR_resnet50clear.txt.2017-07-17_17-50-22
+ exec
++ tee -a experiments/logs/psdb_train_resnet50_--set_EXP_DIR_resnet50clear.txt.2017-07-17_17-50-22
+ echo Logging output to experiments/logs/psdb_train_resnet50_--set_EXP_DIR_resnet50clear.txt.2017-07-17_17-50-22
Logging output to experiments/logs/psdb_train_resnet50_--set_EXP_DIR_resnet50clear.txt.2017-07-17_17-50-22
+ python2 tools/train_net.py --gpu 0 --solver models/psdb/resnet50/solver.prototxt --weights data/imagenet_models/resnet50.caffemodel --imdb psdb_train --iters 50000 --cfg experiments/cfgs/resnet50.yml --rand --set EXP_DIR resnet50clear
('sys.path: ', ['/home/ubuntu/Downloads/protobuf-2.6.1/python/dist', '/home/ubuntu/Downloads/protobuf-2.6.1/python/build/lib.linux-x86_64-2.7', '/home/ubuntu/Downloads/protobuf-2.6.1/python/build/lib.linux-x86_64-2.7/google', '/home/ubuntu/Downloads/protobuf-2.6.1/python/build/lib.linux-x86_64-2.7/google/protobuf', '/home/ubuntu/Downloads/person_search/tools/../lib', '/home/ubuntu/Downloads/person_search/tools/../caffe/python', '/home/ubuntu/Downloads/person_search/tools', '/home/ubuntu/digits', '/home/ubuntu/python', '/home/ubuntu/Downloads/person_search', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/home/ubuntu/Downloads/protobuf-2.6.1/python/build/lib.linux-x86_64-2.7/google/protobuf', '/home/ubuntu/Downloads/protobuf-2.6.1/python/build/lib.linux-x86_64-2.7/google', '/home/ubuntu/Downloads/protobuf-2.6.1/python/build/lib.linux-x86_64-2.7', '/home/ubuntu/Downloads/protobuf-2.6.1/python/dist'])
('protobuf version: ', '3.2.0')
Called with args:
Namespace(cfg_file='experiments/cfgs/resnet50.yml', gpu='0', imdb_name='psdb_train', max_iters=50000, pretrained_model='data/imagenet_models/resnet50.caffemodel', previous_state=None, randomize=True, set_cfgs=['EXP_DIR', 'resnet50clear'], solver='models/psdb/resnet50/solver.prototxt')
Using config:
{'DATA_DIR': '/home/ubuntu/Downloads/person_search/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'resnet50clear',
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MODELS_DIR': '/home/ubuntu/Downloads/person_search/models/pascal_voc',
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/ubuntu/Downloads/person_search',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'NMS': 0.4,
          'PROPOSAL_METHOD': 'selective_search',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'MAX_SIZE': 1000,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 16,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_ITERS': 10000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False},
 'USE_GPU_NMS': True}
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0717 17:50:23.451275 17665 common.cpp:84] You are running caffe compiled with MPI support. Now it's running in non-parallel model
Setting device 0
Loaded dataset `psdb_train` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
done
Preparing training data...
Traceback (most recent call last):
  File "tools/train_net.py", line 122, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "tools/train_net.py", line 75, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "tools/train_net.py", line 72, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/ubuntu/Downloads/person_search/tools/../lib/fast_rcnn/train.py", line 102, in get_training_roidb
    rdl_roidb.prepare_roidb(imdb)
  File "/home/ubuntu/Downloads/person_search/tools/../lib/roi_data_layer/roidb.py", line 31, in prepare_roidb
    roidb[i]['image'] = imdb.image_path_at(i)
IndexError: list index out of range

**Comment by tankienleong** [comment]
I solved the problem after I deleted the cache file in data/cache directory.
