### ISSUE TITLE
Is it possible to run without GUI?

### ISSUE THREAD

**Issue by ChaoqunHong** [ShuangLI59/person_search#57]
Dear authors,

I use putty to run the demo remotely. However, I get the following error.

demo/gallery-1.jpg ...
Traceback (most recent call last):
  File "tools/demo.py", line 114, in <module>
    main(args)
  File "tools/demo.py", line 69, in main
    fig, ax = plt.subplots(figsize=(16, 9))
  File "/home/hong/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 1202, in subplots
    fig = figure(**fig_kw)
  File "/home/hong/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/home/hong/.local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/home/hong/.local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by Cysu** [comment]
Does this stackoverflow [answer](https://stackoverflow.com/questions/37604289/tkinter-tclerror-no-display-name-and-no-display-environment-variable) solve your problem?
