### ISSUE TITLE
Some questions about how to train the dateset

### ISSUE THREAD

**Issue by chr10003566** [ShuangLI59/person_search#72]
I had met some questions about "Experiments: in the ReadME
I had downloaded the  datasets named 'cuhk03_release.zip' and set in the route '/home/tj/Cui/test/person_search/datasets' and  I executed the command
`experiments/scripts/prepare_data.sh /home/tj/Cui/test/person_search/datasets/cuhk03_release.zip`

I got '/home/tj/Cui/test/person_search/data/psdb/cuhk03_release/cuhk-03.mat'
not  in '/path/to/person_search/data/psdb/dataset/annotation/pool.mat' So I got some errors
.After I changed the routes and the name of file, I got the following erros:

Traceback (most recent call last):
  File "tools/train_net.py", line 121, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "tools/train_net.py", line 74, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "tools/train_net.py", line 67, in get_roidb
    imdb = get_imdb(imdb_name)
  File "/home/tj/Cui/test/person_search/tools/../lib/datasets/factory.py", line 24, in get_imdb
    return __sets[name]()
  File "/home/tj/Cui/test/person_search/tools/../lib/datasets/factory.py", line 18, in <lambda>
    __sets[name] = (lambda split=split: psdb(split))
  File "/home/tj/Cui/test/person_search/tools/../lib/datasets/psdb.py", line 34, in __init__
    self._image_index = self._load_image_set_index()
  File "/home/tj/Cui/test/person_search/tools/../lib/datasets/psdb.py", line 403, in _load_image_set_index
    test = loadmat(osp.join(self._root_dir, 'annotation', 'pool.mat'))
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 134, in loadmat
    MR = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    raise NotImplementedError('Please use HDF reader for matlab v7.3 files')
NotImplementedError: Please use HDF reader for matlab v7.3 files
 
Question: 
This ‘cuhk-03.mat’ is just unziped from the original file. Is there any error in the original file. Need I get the original dataset from you?

**Comment by Cysu** [comment]
Sorry but you need to send email to me (tong.xiao.work [at] gmail.com) to get our dataset. We don’t support cuhk03, which is for person reid not person search.
