### ISSUE TITLE
How to modify the eval_test.sh in cpu_only

### ISSUE THREAD

**Issue by gcy2231192** [ShuangLI59/person_search#82]
I run it in cpu_only using experiments/scripts/eval_test.sh resnet50 50000 resnet50
but i have error:
Traceback (most recent call last):
  File "tools/eval_test.py", line 158, in <module>
    main(args)
  File "tools/eval_test.py", line 51, in main
    imdb = get_imdb(args.imdb_name)
  File "/home/wsn/person_search/tools/../lib/datasets/factory.py", line 24, in get_imdb
    return __sets[name]()
  File "/home/wsn/person_search/tools/../lib/datasets/factory.py", line 18, in <lambda>
    __sets[name] = (lambda split=split: psdb(split))
  File "/home/wsn/person_search/tools/../lib/datasets/psdb.py", line 34, in __init__
    self._image_index = self._load_image_set_index()
  File "/home/wsn/person_search/tools/../lib/datasets/psdb.py", line 403, in _load_image_set_index
    test = loadmat(osp.join(self._root_dir, 'annotation', 'pool.mat'))
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
TypeError: 'NoneType' object is not iterable

**Comment by gcy2231192** [comment]
don't unzip dataset
