### ISSUE TITLE
run demo.py

### ISSUE THREAD

**Issue by zhenzhen9202** [ShuangLI59/person_search#84]
demo/gallery-1.jpg ...
Traceback (most recent call last):
  File "tools/demo.py", line 114, in <module>
    main(args)
  File "tools/demo.py", line 70, in main
    ax.imshow(plt.imread(gallery_img))
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 2177, in imread
    return _imread(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/image.py", line 1242, in imread
    im = pilread(fname)
  File "/usr/lib/pymodules/python2.7/matplotlib/image.py", line 1223, in pilread
    return pil_to_array(image)
  File "/usr/lib/pymodules/python2.7/matplotlib/image.py", line 1328, in pil_to_array
    x = toarray(im)
  File "/usr/lib/pymodules/python2.7/matplotlib/image.py", line 1314, in toarray
    x = np.fromstring(x_str, dtype)
TypeError: fromstring() argument 1 must be string or read-only buffer, not None

**Comment by 435981572** [comment]
’hello ,are you in China ?I 'am in Shaanxi Provence ,recently ,I  can't download the dataset of this paper ,could you send me the dataset ?thanks a lot .

**Comment by Cysu** [comment]
@zhenzhen9202 Did you change the demo code?

@435981572 Please send email to me, through your institution email. Thanks.
